import BottomNav from "./BottomNav";
import BottomTrending from "./BottomTrending";
import BottomHome from "./BottomHome";
import BottomProfile from "./BottomProfile";
import HomeStack from "./HomeStack";
import About from "./About";
import Payment from "./Payment";
import Privacy from "./Privacy";
import Terms from "./Terms";
import Settings from "./Settings";
export {BottomNav, BottomTrending,BottomHome, BottomProfile,HomeStack, Payment, About, Privacy, Terms, Settings};
